### ISSUE TITLE
Causal query gets stuck in "loading"

### ISSUE THREAD

**Issue by zzwonder** [tum-i22/causal-canvas#18]
Hi,

I am new to causal reasoning and was trying to play with causal-canvas. I ran the executable version of causal-canvas on Windows 10 and MacOS by the corresponding package (win-x32-64 and darwin-x32). Nevertheless, when I loaded a model and clicked the pensil icon, the following error message appeared:

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'setModel' of undefined
at EventEmitter.HP2SATConnector.setModel (webpack:///./src/hp2satConnector.ts?:49:26)
at EventEmitter.emit (events.js:182:13)
at WebContents.<anonymous> (/private/var/folders/cy/4d8smhfn2ld27w61smjvj9080000gn/T/AppTranslocation/F11423DF-1655-47C4-8DCD-0D759F3BF09A/d/causal-canvas.app/Contents/Resources/electron.asar/browser/api/web-contents.js:284:13)
at WebContents.emit (events.js:182:13)

After ignoring the error message I can still select the "content", "cause" and "phi". However, when I clicked "Query", I can only see "loading" in the place which is supposed to show the result. Do you have any clue why this is happening? Thank you!

**Comment by amjadKhalifah** [comment]
Hello,
Thanks for your report. I just tried the canvas and was not able to reproduce. I downloaded the package on a win 10 machine and the from help opened the example. One thing to note is that the canvas starts a local server with these settings (localhost:4040). I am guessing your machines are blocking such ports/requests or maybe a machine naming issue. Could you check if there are any processes running on the port after you open-up the canvas. 
On windows this is the command: `netstat -ano | findstr 4040`

Best,
Amjad

**Comment by zzwonder** [comment]
Hi Amjad,

Thank you very much for the timely reply! I ran the command on a Windows 10 machine but it returns nothing.

I tested causal-canvas on two Windows 10 machines. On both of the machines, an error message jumped out just after causal-canvas was opened up. 

![image](https://user-images.githubusercontent.com/45185698/170774058-2a8710d7-3936-40c4-ad89-5c67744dec28.png)

I am wondering if any external packages are necessary to be installed to run causal-canvas. Thank you.

Zhiwei

**Comment by amjadKhalifah** [comment]
Hello Zhiwei, 
If the command is not returning a running process on port 4040, the the issue is about starting the Java backend on the machine. This indeed requires a Java run-time (or a JDK) on the machine, see, e.g.,: https://www.guru99.com/install-java.html
Please let me know so that I update the documentation to mention this as well. 
Thanks!
Amjad

**Comment by zzwonder** [comment]
Hi Amjad,

I installed java runtime from java.com for both my Windows and Mac machines and causal-canvas worked on both! Thank you very much for the help!

Zhiwei
